// import type { Metadata } from "next"; // Keep this if you need Metadata
// import { Geist, Geist_Mono } from "next/font/google"; // COMMENT OUT or REMOVE this line
import "./globals.css";
import type { Metadata } from "next"; // Add this line
// import { Inter } from "next/font/google"; // Your existing import
// import "./globals.css"; // Your existing import

// COMMENT OUT or REMOVE these blocks:
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`} // COMMENT OUT or REMOVE font variables
        className="antialiased" // Keep 'antialiased' if desired
      >
        {children}
      </body>
    </html>
  );
}